print('~~~~~~~~~~TABUADA~~~~~~~~')
nu=int(input('digite o numero a ser consultado'))
print('#####Resultado#####')
print("{} X 1 ={}".format(nu,nu*1))
print("{} X 2 ={}".format(nu,nu*2))
print("{} X 3 ={}".format(nu,nu*3))
print("{} X 4 ={}".format(nu,nu*4))